project_id = "yuavzvlynsqrkbuzmcra"

[functions.shopify-order-webhook]
verify_jwt = false

[functions.shopify-customer-webhook]
verify_jwt = false

[functions.bling-oauth-callback]
verify_jwt = false
